CREATE DATABASE MYDATABASE

USE MYDATABASE

--ONE TO ONE

CREATE TABLE PHONE(
ID INT PRIMARY KEY IDENTITY,
PHONENAME NVARCHAR(50)
)

CREATE TABLE SIMCARD(
ID INT PRIMARY KEY IDENTITY REFERENCES PHONE(ID),
SIMCARDNAME NVARCHAR(50)
)

INSERT INTO PHONE 
VALUES
('IPHONE'),
('SAMSUNG'),
('XIAOMI')

DBCC CHECKIDENT('SIMCARD', RESEED, 3);

INSERT INTO PHONE(PHONENAME)
VALUES ('TECHNO');

DELETE FROM PHONE
WHERE ID IN (5)

INSERT INTO SIMCARD 
VALUES
('AZERCELL'),
('BAKCELL'),
('AZERFON')

INSERT INTO SIMCARD
VALUES
('AZERCELL')

SELECT * FROM PHONE
SELECT * FROM SIMCARD

SELECT * FROM PHONE AS PH
INNER JOIN SIMCARD AS SC
ON PH.ID = SC.ID

-- ONE TO MANY
CREATE TABLE COUNTRY(
ID INT PRIMARY KEY IDENTITY,
COUNTRYNAME NVARCHAR(50)
)

CREATE TABLE FOOTBALLCLUB(
FOOTBALLCLUBID INT PRIMARY KEY IDENTITY,
FOOTBALLCLUBNAME NVARCHAR(50),
COUNTRYID INT FOREIGN KEY REFERENCES COUNTRY(ID)
)

INSERT INTO COUNTRY
VALUES
('AZERBAIJAN'),
('TURKEY'),
('GERMANY'),
('ITALY'),
('FRANCE')

INSERT INTO FOOTBALLCLUB
VALUES
('NEFTCHI',1),
('GARABAGH',1),
('GALATASARAY',2),
('FENERBAHCE',2),
('TRABZONSPOR',2),
('BAYERN',3),
('DORTMUND',3),
('ROMA',4),
('INTER',4),
('MILAN',4),
('JUVENTUS',4),
('LYON',5),
('PSG',5),
('MONAKO',5)

SELECT * FROM COUNTRY
SELECT * FROM FOOTBALLCLUB

SELECT * FROM COUNTRY AS CT
INNER JOIN FOOTBALLCLUB AS FC
ON CT.ID = FC.COUNTRYID

--MANY TO MANY

CREATE TABLE STUDENT(
ID INT PRIMARY KEY IDENTITY,
STUDENTNAME NVARCHAR(50)
)

CREATE TABLE COURSE(
ID INT PRIMARY KEY IDENTITY,
COURSENAME NVARCHAR(50)
)

CREATE TABLE ENROLLMENT(
ID INT PRIMARY KEY IDENTITY,
STUDENTID INT FOREIGN KEY REFERENCES STUDENT(ID),
COURSEID INT FOREIGN KEY REFERENCES COURSE(ID)
)

INSERT INTO STUDENT
VALUES
('SAHIB'),
('FAIQ'),
('ILKIN'),
('BEHRUZ')

INSERT INTO COURSE
VALUES
('C#'),
('JAVA'),
('JS'),
('C++')

INSERT INTO ENROLLMENT
VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(2,4)

SELECT * FROM STUDENT
SELECT * FROM COURSE
SELECT * FROM ENROLLMENT

SELECT STUDENT.ID, STUDENT.STUDENTNAME, COURSE.COURSENAME FROM ENROLLMENT 
INNER JOIN STUDENT ON ENROLLMENT.STUDENTID = STUDENT.ID
INNER JOIN COURSE  ON ENROLLMENT.COURSEID = COURSE.ID;


